name: Win11Desktop
options:
  bundleIdPrefix: com.win11desktop
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  Win11Desktop:
    type: application
    platform: macOS
    sources:
      - path: Win11Desktop
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.win11desktop.app
        INFOPLIST_FILE: Win11Desktop/Info.plist
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: "Win11 Desktop"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_ENTITLEMENTS: Win11Desktop/Win11Desktop.entitlements
    entitlements:
      path: Win11Desktop/Win11Desktop.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true

schemes:
  Win11Desktop:
    build:
      targets:
        Win11Desktop: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
